"""An explicitly scripted, fictional rehearsal; never a substitute for live output."""
import json
from engine import STAGES, LIST_FIELDS

ARTIFACTS = {
"understand": ("Problem brief", "Problem: New team leads may avoid, overgeneralize, or mishandle difficult feedback conversations. Course completion does not establish readiness.\n\nCapability hypothesis: A lead can name observable behavior, check their interpretation, invite the other person's account, agree on an actionable next step, and recognize when escalation or a system change is appropriate.\n\nPeople: leads and colleagues affected by their decisions, managers, learning teams, and employee representatives. Their voice is absent in this fictional rehearsal and must be obtained before piloting.\n\nRival explanations: impossible workloads, unclear authority, poor incentives, ambiguous role expectations and lack of protected time. Training cannot repair these alone.\n\nBaseline: inspect voluntary, de-identified work samples and conduct interviews before selecting an intervention. No participant evidence exists yet. Success would be better conversations and recovery under realistic constraints, with agency, dignity and sustainable workload preserved."),
"model": ("Coupled capability requirements", "Human requirement: Separate an observation from an interpretation; check context; listen; propose a feasible next action; recognize a concern that belongs with an accountable owner. Practice must include disagreement and incomplete information.\n\nSystem requirement: Provide protected practice time, an accessible interface, private draft space, source-visible guidance, a correction path, a non-AI fallback and clear limits on manager access.\n\nCausal hypothesis: Contextual practice plus credible feedback improves judgment; judgment transfers only if workload, authority and supervision permit it. Better task evidence may then support better operational outcomes. These links are hypotheses.\n\nAuthority: Employees control whether a practice artifact is shared. Managers cannot use this tool to rank or certify employees. The learning team curates prompts; a human reviews ambiguous evidence.\n\nFailure: Polished writing can conceal poor judgment. Learners might comply with advice rather than understand it. Missing practice evidence means unknown readiness, not a deficit."),
"design": ("Options and tradeoffs", "Option A: A manager-led role-play with a paper checklist. Advantages: interpersonal realism and no model dependency. Drawbacks: time and variable feedback quality.\n\nOption B: A private structured practice workbench with curated scenarios. Advantages: repeatable access, inspectable prompts and a low-data design. Drawbacks: it cannot observe a real conversation or judge interpersonal competence.\n\nOption C: An AI coach offering open-ended advice. Advantages: variation and conversational response. Drawbacks: advice can be overconfident, reflect bias, or encourage recording sensitive employee details.\n\nSelected candidate: B plus voluntary manager role-play. Keep A as the comparison. Treat C as a separately reviewed optional extension, not a prerequisite.\n\nTradeoff: Contextual detail helps feedback but increases privacy risk; use fictional situations and learner-written abstractions. Scaling practice saves expert time only if meaningful review survives.\n\nDecision: Build the narrow workbench, collect no identifiable records, and obtain affected-person review before any pilot. This is a candidate design, not institutional approval."),
"build": ("Feedback practice workbench", "Implemented practice artifact: Open Practice in this workbench. Select a fictional challenge, separate an observation from an interpretation, plan an opening question, an agreed next step and an escalation boundary. Introduce a counterexample and revise the plan. Export the learner's own notes if wanted.\n\nFeedback is a transparent structure check. It does not score competence or claim that text length predicts performance. All entries stay in the page until the learner downloads them; no employee records or conversation recordings are required.\n\nNon-AI fallback: Print the scenario and prompts and conduct the practice with a colleague. A lead should be able to explain their judgment without relying on an automated response.\n\nTechnical boundary: The practice tool is executable; the project deliberation is a separate record. The hosted viewer replays saved runs. Live agent generation is provided by the local runner.\n\nHuman capability: Explain, listen, revise and escalate. System capability: Make guidance, uncertainty and sharing boundaries visible. Remaining validation: accessibility with affected users and quality of conversation practice."),
"instrument": ("Measurement and transfer plan", "Before piloting, agree on observable judgments with practitioners and affected colleagues. Use fictional work samples and voluntary role-play to inspect observation versus inference, listening, next-step feasibility and escalation. Do not turn these into an automated employment score.\n\nComparison: Use the manager-led paper practice as the non-AI baseline. Record practice opportunity and workload so increased exposure is not mistaken for a tool effect.\n\nTransfer: Inspect a later, unfamiliar scenario and optional de-identified reflection on work. Distinguish immediate practice quality, retained capability and operational outcomes.\n\nFlourishing: Ask whose agency grows, whether colleagues experience dignity and voice, who lacks accessible practice time, and whether the intervention changes workload or trust. Absence of a complaint is not evidence of safety.\n\nEvidence ledger: task quality unknown; transfer unknown; trust unknown; burden unknown; subgroup coverage unknown. Report missingness beside findings. No fabricated percentages or aggregate readiness score.\n\nDisconfirmation: Better written answers with worse live listening, no transfer, or surveillance pressure invalidates the mechanism. Revisit Model or Understand rather than merely tuning a score."),
"deploy": ("Human-reviewed pilot plan", "Status: pending human approval. This rehearsal deploys only the demonstration software, not an intervention to an organization.\n\nRequired owners: learning engineer, accountable operational sponsor, affected-person representatives and data-governance owner. They must approve purpose, participation, data minimization, accessibility, comparison and stopping rules.\n\nInvite voluntary participation with protected time. Preserve the paper practice route. Make sharing granular and revocable; no employee ranking, automatic readiness certification or hidden manager analytics.\n\nBefore collecting evidence: agree on the retention/deletion policy, what participants may decline and who can inspect each record. Do not copy personal employee cases into an AI prompt.\n\nStop or redesign if practice becomes compulsory disclosure, workload displaces meaningful work, access barriers exclude a group, or managers treat missing evidence as poor performance.\n\nRecovery: Suspend the pilot and retain a decision log of the design changes. Keep the functioning non-AI practice path available."),
"evaluate": ("Evidence review with explicit unknowns", "No pilot has occurred. This review evaluates design coverage and failure hypotheses; it cannot claim capability growth, transfer, operational benefit or human flourishing.\n\nObserved software fact: A visitor can use a structured practice tool and inspect the saved lifecycle journal. That fact does not establish a learning effect.\n\nHypothesis review: Practice may improve difficult-conversation judgment if the task is authentic and feedback is credible. Rival causes include manager attention, protected time and changed incentives.\n\nPending evidence: affected-person acceptance, accessibility, conversation quality, transfer, workload, privacy experience and subgroup coverage. Every field remains unknown until collected with consent.\n\nDecision: Do not scale or announce success. Seek review of the pilot design. If the capability model fails to explain real difficulties, return to Understand; if the tool changes nothing despite a valid model, return to Design.\n\nDissent retained: Managers may demand assurance before granting practice time. The system must make evidence uncertainty visible without converting it into surveillance."),
"refine": ("Revised project and next learning question", "Revision: The candidate is a private practice tool paired with voluntary human role-play, supported by explicit limits on evidence sharing and a protected-time requirement. A capability map guides task selection; it is not a ranking system.\n\nScenario lesson: A sponsor's request for an employee readiness leaderboard invalidates the assumption that development evidence will remain developmental. Another scenario removes protected practice time during a staffing shortage. Both require system and governance changes, not more content.\n\nWhat changed: Move authority and sharing requirements into Model. In Design retain the paper route and revise practice scheduling and data boundaries. In Instrument treat uneven opportunity as an explanation for missing evidence.\n\nNext question: Do affected leads and colleagues accept the capability model, and can they practice within real workload constraints? Use that answer to choose whether to pilot, redesign the work context or abandon the intervention.\n\nStatus: Candidate solution ready for human review; no organizational pilot or efficacy claim. Preserve dissent, rejected options, scenario links and earlier artifact revisions so a visitor can inspect the basis for this decision."),
}

EXPERTS = {
"domain": "The real task is conducting a difficult conversation while preserving the colleague's voice. Domain assumptions need interviews with actual leads and colleagues. Do not assume avoidance is a knowledge deficit: unclear authority or incentives may explain it.",
"design": "Invite affected colleagues into framing. A manager's account is not enough. Practice must support accessible participation, refusal and a private draft. A polished script can still feel coercive in a real conversation.",
"systems": "Specify what people must do and what the organization must enable. Protected time, clear authority and recovery are system requirements. Missing opportunities cannot fairly be interpreted as low employee capability.",
"learning": "Use practice on observable judgments, variation and feedback, followed by an unfamiliar transfer task. An attractive answer or completed module is weak evidence. Preserve a human role-play route so listening and revision can be observed.",
"responsible": "Development data could become surveillance even when the original purpose is supportive. Keep manager access optional and granular, forbid ranking, and make refusal possible. Advice must remain challengeable and consequential decisions human-owned.",
"implementation": "Build a narrow, usable practice tool with fictional scenarios and local notes. Show precisely what the structure check checks. Keep a paper fallback. The replay surface must expose stage revisions without showing future artifacts early.",
"measurement": "Separate practice quality, retained capability, transfer and operational outcomes. Compare with paper role-play and account for protected time. No field evidence exists here; unknown values must not become zeros or simulated gains.",
}

class ScriptedProvider:
    mode = "scripted-simulation"
    def call(self, role, stage, prompt, directory, ordinal):
        # Read only supplied public context; make the fixture's limitations explicit.
        import re
        context = json.loads(prompt.split("RECENT PUBLIC DISCUSSION: ", 1)[1].splitlines()[0])
        response = {"message": "", **{k: [] for k in LIST_FIELDS}, "artifact_title": "", "artifact_body": "", "prototype_html": "", "decision": "", "revisit_stage": "", "challenged_assumption": "", "evidence_refs": [t["seq"] for t in context[-3:]]}
        match = re.search(r"responding to (?:scenario|review trigger) sequence (\d+)", prompt)
        trigger = int(match.group(1)) if match else None
        if role == "scenario":
            response.update(message="Hypothetical objection: The sponsor asks for a readiness leaderboard to decide promotions. Employees say private practice will now feel like a test with consequences." if stage == "design" else "Hypothetical unexpected event: A staffing shortage removes protected practice time. Participation falls unevenly across shifts; a manager calls the missing evidence a capability gap.", challenged_assumption="Development evidence will remain developmental and voluntary." if stage == "design" else "All leads have a fair opportunity to practice.", revisit_stage="model" if stage == "design" else "design", decision="Return to authority and sharing requirements." if stage == "design" else "Return to the intervention and work-context design.")
        elif role == "orchestrator":
            title, body = ARTIFACTS[stage]
            response.update(message=f"I am retaining the specialist's concern and updating {title.lower()}. The candidate must couple human capability with what the work system enables. Agent agreement is not stakeholder approval.", artifact_title=title, artifact_body=body, decision="Continue the rehearsal; real evidence and human review remain pending.")
            if stage == "build":
                response["prototype_html"] = '''<!doctype html><html lang="en"><meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;color:#172135;padding:20px;line-height:1.6}button,select{font:inherit;padding:10px;margin:10px 0;border:1px solid #63728b;border-radius:5px}#feedback{background:#e9f5f2;padding:15px}label{display:block}</style><h2>Observation or interpretation?</h2><p>A handoff arrived late. You have not heard your colleague's account.</p><label for="choice">Which statement opens an inquiry?</label><select id="choice"><option value="">Choose your opening</option><option value="inference">You do not care about the team.</option><option value="observation">The handoff arrived after the agreed time. What happened?</option></select><button id="review">Examine the choice</button><p id="feedback" role="status">Choose before seeing feedback.</p><p>Counterexample: the deadline was changed in a channel your colleague could not access. How would your next step change?</p><p>This fictional practice offers transparent feedback on one choice. It does not establish competence. Practice listening and revision with a colleague using a paper scenario.</p><script>document.getElementById('review').onclick=()=>{const v=document.getElementById('choice').value;document.getElementById('feedback').textContent=v==='observation'?'This names an event and leaves room for an account. Your inference still needs checking.':v==='inference'?'This attributes a motive without evidence. Start with the observation and invite their account.':'Select an opening first.';};</script></html>'''
            if trigger:
                response["evidence_refs"] = list(dict.fromkeys([*response["evidence_refs"], trigger]))
                response["message"] = "The scenario invalidates a system assumption. I am revising the earlier artifact and preserving the original, rather than treating the event as a learner deficit."
                response["artifact_body"] += "\n\nScenario-driven revision: " + ("Employees own disclosure. No readiness leaderboard or promotion use is permitted. An accountable owner must enforce purpose boundaries and hear employee objections before piloting." if stage == "model" else "Protected time is a prerequisite, not an assumed employee resource. Offer short voluntary practice or paper role-play, record opportunity differences, and postpone the pilot if workload makes practice infeasible.")
                response["decision"] = "Revise requirements and seek affected-person review before a real pilot."
                if stage in ("design", "evaluate") and context[-1]["agent"] == "scenario":
                    response["revisit_stage"] = "model" if stage == "design" else "design"
                    response["decision"] = "Accept the scenario's challenge and return to " + response["revisit_stage"] + ". Preserve the objection and require human review."
        else:
            response.update(message=EXPERTS[role], artifact_title=f"{role.capitalize()} review", artifact_body=EXPERTS[role], decision="Ask the learning engineer to preserve this constraint in the stage artifact.")
        response["advantages"] = ["Task-specific practice can make the capability requirement visible."]
        response["drawbacks"] = ["A text workbench cannot observe authentic interpersonal performance."]
        response["tradeoffs"] = ["Richer context improves relevance but can increase disclosure and workload."]
        response["risks"] = ["A development tool may be repurposed for surveillance or blame."]
        response["human_capabilities"] = ["Distinguish observation from inference; listen, revise and escalate."]
        response["system_capabilities"] = ["Provide protected practice time, accessible guidance and controlled sharing."]
        response["flourishing"] = ["Test agency, dignity, voice, equitable opportunity and sustainable workload with affected people."]
        response["objections"] = ["Managers may demand a score; colleagues may distrust the stated purpose."]
        return response, {"provider": "authored-script", "model_requested": "none", "fixture": "fictional workforce rehearsal", "note": "Scripted public discussion; no model-generated turns or field observations."}
